name = "ExamplePackage"
uuid = "d4fbd86c-284f-11e9-18e3-552ea2674abd"
authors = ["Phoenix Zhang <pho.coderzhang@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
